import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import TemplesTable from "../components/TemplesTable";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <Hero />
        <div className="circles">
          <div className="circle-div first-circle" />
          <div className="circle-div second-circle" />
        </div>
        <div>
          <TemplesTable />
        </div>
      </main>
    </>
  );
}
