import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {

  // Read the csv file from the public folder
  const res = await fetch('http://localhost:3000/temples.csv')
  const data = await res.text()

  // Split the csv file into an array of rows
  const rows = data.split('\n')


  return {
    props: { temples: rows }
  }
}

const Names = ({ temples }) => {
  return (
    <>
      <Head>
        <title>Thai temples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={inter.className}>

          {temples.map((temple, index) => (
            <div key={index}>
              <p>{temple}</p>

            </div>
          ))}

        </div>

      </main>
    </>
  );
};

export default Names;